### ISSUE TITLE
Additional builds

### ISSUE THREAD

**Issue by averyanalex** [popura-network/Popura#15]
Please, add additional builds, busybox amd64 and busybox armv8 and etc

**Comment by averyanalex** [comment]
It is for docker alpine

**Comment by zhoreeq** [comment]
Do you want to use pre-built binaries in the Docker container?

There is a docker file, I think it builds a binary by itself https://github.com/popura-network/Popura/tree/master/contrib/docker

**Comment by averyanalex** [comment]
Yes, thanks. If I will do something, I will write on Mesh forum (I'm about Addon)
