### ISSUE TITLE
Add ppa repository

### ISSUE THREAD

**Issue by averyanalex** [popura-network/Popura#16]
Please, can you add ppa repository for popura? And maybe AUR

**Comment by zhoreeq** [comment]
I don't know how to do that yet, but it can be added.

**Comment by averyanalex** [comment]
I am too, but need something "Makefile" if I know. Then we can have .changes file and send it to ppa. Similar way to AUR.

**Comment by rany2** [comment]
If you're on Arch you could now use https://aur.archlinux.org/packages/popura-git/

**Comment by rany2** [comment]
If you're on Arch you could now use https://aur.archlinux.org/packages/popura-git/  

It installs the following binaries `popura` and `popuractl`. It doesn't use `yggdrasil` and `yggdrasilctl` so you could have yggdrasil and popura packages installed at the same time.

Config is at `/etc/popura.conf`. To enable, autopeering you could modify `popura`'s options in `/etc/default/popura` to add autopeer. 

systemd service is called `popura.service` so you'll have to enable and start that.

**Comment by rany2** [comment]
Now we have an official popura repo on https://github.com/popura-network/popura-debian-repo  

I think this issue should be closed

**Comment by zhoreeq** [comment]
Awesome!
