### ISSUE TITLE
Why Popura?

### ISSUE THREAD

**Issue by averyanalex** [popura-network/Popura#17]
Why you didn't contributed to yggdrasil and create a fork?

**Comment by zhoreeq** [comment]
Yggdrasil developers have a different vision for their project, they are more focused on experimenting with the routing protocol. They want to keep their code base minimal, which I respect.

I wanted some extra features for Yggdrasil, more practical things like autopeering and RAdv. So, there's this repo. It's not competing with the upstream, but complements it.

**Comment by averyanalex** [comment]
Understood, how about yggdrasilgui? And yes, HJSON not very "comfortable", what about YAML? It will be much easier to set peers. And you can separate yggdrasil.conf and popura.conf, maybe /etc/yggdrasil directory

**Comment by zhoreeq** [comment]
@averyanalex I will think about that. Right now Popura config is fully compatible with yggdrasil. The main down side of custom configuration format is that it will require to also create custom OS packages, which is a lot of work.

GUI is in the roadmap :+1:
