### ISSUE TITLE
Add AUR enhancements to Popura

### ISSUE THREAD

**Issue by rany2** [popura-network/Popura#19]
I've made a few enhancements to systemd service and apparmor which I'd like to push upstream. These changes are used in AUR and I'd like to put them here.

for systemd service the only change is adding `/etc/default/popura` environment variable file to pass arguments to popura. (important for autopeer)

https://aur.archlinux.org/packages/popura-git/

Clone `https://aur.archlinux.org/popura-git.git` to get the modified files.

**Comment by zhoreeq** [comment]
You may be asking, why wasn't everything named `popura` in the first place?

Let me clarify. It's not really a new program, think of it as "Yggdrasil Professional Edition" (like if Microsoft made it 😂). The idea here is to have as much compatibility with other Yggdrasil tools and packages as possible. To keep focus on implementing new features, reusing everything else from yggdrasil almost unchanged.

It's up to you how things will be named in Arch package, but if you ask me, I'd like to keep everything close to the upstream.

**Comment by rany2** [comment]
I understand.  I'll fix the AUR to conflict with yggdrasil package and use all files from contrib. I misunderstood your intention
