### ISSUE TITLE
Пофиксить ошибку с последними сборками Windows (21h1)

### ISSUE THREAD

**Issue by IvanGorinich-GitHub** [popura-network/Popura#22]
![изображение](https://user-images.githubusercontent.com/64200268/114921433-9aa9a400-9e3b-11eb-8ec6-4e096dcd2eb1.png)

Эта ошибка возникает даже с правами администратора. Протестировано на нескольких компьютерах под управлением Windows 10 21H1

**Comment by zhoreeq** [comment]
https://github.com/yggdrasil-network/yggdrasil-go/issues/771

**Comment by zhoreeq** [comment]
Как временное решение, надо сначала установить старую версию 0.3.15, а поверх нее уже 0.3.16
