### ISSUE TITLE
Переименуй Minecraft сборку

### ISSUE THREAD

**Issue by IvanGorinich-GitHub** [popura-network/Popura#25]
Я предлагаю переименовать сборку Minecraft, просто это название сбивает с толку, и из-за этого могут быть конфликты с Microsoft. Как пример Popura Auto, или Popura Light

**Comment by zhoreeq** [comment]
Popura Pro Gamer Edition

**Comment by zhoreeq** [comment]
https://github.com/popura-network/Popura/releases/tag/v0.4.2%2Bauto1

Теперь сборка называется Yggdrasil Auto
