### ISSUE TITLE
Автоматическое включение Meshname в сборке Minecraft

### ISSUE THREAD

**Issue by IvanGorinich-GitHub** [popura-network/Popura#26]
Я бы хотел чтобы после установки Minecraft сборки, автоматически включался установочный скрипт meshname, ну или meshname сам устанавливался под нужную систему.

**Comment by zhoreeq** [comment]
Сделано, мешнейм включен по-умолчанию в minecraft сборке

https://github.com/popura-network/Popura/releases/tag/v0.4.0%2Bpopurame3
