### ISSUE TITLE
Keep HJSON comments in config

### ISSUE THREAD

**Issue by zhoreeq** [popura-network/Popura#4]

**Comment by averyanalex** [comment]
What do you mean? I think I can help...

**Comment by zhoreeq** [comment]
There are 2 separate config structs, YggdrasilConf and PopuraConf.  To save the config file those structs need to be combined to a single one. There might be another way to extend YggdrasilConf with custom options, but I don't know any better way. The goal is to keep the config file format compatible with the original software.

The way it works right now, [HJSON comments are lost due to "double serialization" hack](https://github.com/popura-network/Popura/blob/master/src/popura/config.go#L75).
