### ISSUE TITLE
вопросы

### ISSUE THREAD

**Issue by whoizit** [popura-network/Popura#7]
1. не понимаю, зачем это нужно формализовывать в конфиге, если это константа высчитываемая из ipv6 адреса? или я могу написать любую строку и оно будет резолвить на мой ygg-ipv6 адрес? Не понятно для чего эта конструкция.

```
    Config: {
        "string": [
            "string.meshname. AAAA <ygg-ipv6>"
        ]   
    }
```

2.  можно ли настраивать поддомены в этом конфиге? Если нет, то следует привести пример использования сабдоменов на примере dnsmasq
3. могу ли я вместо .meshname писать .ygg чтоб это резолвилось у других?

**Comment by zhoreeq** [comment]
1. 
> или я могу написать любую строку и оно будет резолвить на мой ygg-ipv6 адрес?

Верно, можно указать несколько псевдо-доменов, которые обслуживаются этой нодой. 
```
{
        "amcrxoqgun7siaaaaaaaaaaaem":[
                "amcrxoqgun7siaaaaaaaaaaaem.meshname. AAAA 305:1bba:6a3:7f24::23"
        ],
        "amcrxoqgun7siaaaaaaaaaaaeq":[
                "amcrxoqgun7siaaaaaaaaaaaeq.meshname. AAAA 305:1bba:6a3:7f24::24"
        ],
        "amcrxoqgun7siaaaaaaaaaabaa":[
                "amcrxoqgun7siaaaaaaaaaabaa.meshname. AAAA 305:1bba:6a3:7f24::100"
        ]
}
```

2. В массиве добавляются нужные поддомены, напр.

```

  Meshname:
  {
    Config:
    {
      aicrxoqgun7siwm42akzfsox7m:
      [
        aicrxoqgun7siwm42akzfsox7m.meshname. AAAA 205:1bba:6a3:7f24:599c:d015:92c9:d7fb                                                                                  
        test.aicrxoqgun7siwm42akzfsox7m.meshname. AAAA 205:1bba:6a3:7f24:599c:d015:92c9:d7fb                                                                             
        aicrxoqgun7siwm42akzfsox7m.ygg AAAA 205:1bba:6a3:7f24:599c:d015:92c9:d7fb                                                                                        
        _xmpp-client._tcp.aicrxoqgun7siwm42akzfsox7m.ygg. 86400 IN SRV 5 0 5222 xmpp.aicrxoqgun7siwm42akzfsox7m.ygg.                                                     
        _xmpp-server._tcp.aicrxoqgun7siwm42akzfsox7m.ygg. 86400 IN SRV 5 0 5269 xmpp.aicrxoqgun7siwm42akzfsox7m.ygg.                                                     
        xmpp.aicrxoqgun7siwm42akzfsox7m.ygg. AAAA 305:1bba:6a3:7f24::23
        anon.aicrxoqgun7siwm42akzfsox7m.ygg. AAAA 305:1bba:6a3:7f24::23
        conference.aicrxoqgun7siwm42akzfsox7m.ygg. AAAA 305:1bba:6a3:7f24::23
      ]
    }
    Enable: true
    Listen: "[::1]:53535"
  }
```

3. Да, в сборке включены и .meshname и .ygg

**Comment by zhoreeq** [comment]
Документация почти такая же как и у meshname, добавлю потом в вики это https://github.com/zhoreeq/meshname#example-configuration-file

**Comment by whoizit** [comment]
теперь всё понятно, спасибо. Круто

**Comment by whoizit** [comment]
Почему не заходишь к нам в meshnet? https://github.com/russian-meshnet/meshnet-chat-agenda#чаты-и-мосты-в-разных-сетях

**Comment by zhoreeq** [comment]
@whoizit я через матрицу у вас, просто ридонли)

**Comment by averyanalex** [comment]
Я буду делать Discord сервер про Mesh сети, со ссылками, гайдами и т.п.
